# Use Cayman theme for full-width modern rendering
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Markdown settings - use GFM for better rendering
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
  
# GitHub Pages settings
github:
  is_project_page: false
  
# Site settings
title: ""
description: ""
  
