# Use minimal theme for clean rendering
theme: jekyll-theme-minimal

# Markdown settings - ensure proper HTML rendering
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  auto_ids: true
  syntax_highlighter: rouge
  
# Site settings - disable showing title from config
show_downloads: false

# GitHub Pages settings
github:
  is_project_page: false
  
